# Generated by Django 5.2 on 2025-04-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagyodenpyo', '0006_worklog_work_order_alter_worklog_work_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='work_order',
        ),
    ]
