# Generated by Django 5.1.5 on 2025-04-23 07:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyodenpyo', '0007_remove_worklog_work_order'),
        ('sagyoshiji', '0022_alter_workorder_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='work_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='sagyoshiji.workorder', verbose_name='作業指示票'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='work_hours',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='work_minute',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='分'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='work_trenum',
            field=models.CharField(default='', max_length=3, verbose_name='枝番'),
        ),
    ]
