# Generated by Django 5.1.5 on 2025-04-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyodenpyo', '0009_alter_worklog_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='subject',
            field=models.CharField(default='', max_length=20, verbose_name='件名'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='work_number',
            field=models.CharField(default='', max_length=4, verbose_name='工番'),
        ),
    ]
