# Generated by Django 5.1.5 on 2025-04-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyodenpyo', '0011_alter_worklog_work_order'),
        ('sagyoshiji', '0022_alter_workorder_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='work_order',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='sagyoshiji.workorder', verbose_name='作業指示票'),
        ),
    ]
