# Generated by Django 5.1.5 on 2025-04-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagyodenpyo', '0017_alter_worklog_work_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='work_order',
        ),
    ]
