# Generated by Django 5.1.5 on 2025-04-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyodenpyo', '0018_remove_worklog_work_order'),
        ('sagyoshiji', '0022_alter_workorder_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='work_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sagyoshiji.workorder'),
        ),
    ]
